#define HEPNOS_FOREACH_NOVA_CLASS \
  X(hep::rec_energy_nue) \
  X(hep::rec_energy_nue_lid) \
  X(hep::rec_energy_numu) \
  X(hep::rec_energy_numu_bpfenergy) \
  X(hep::rec_energy_numu_hadclust) \
  X(hep::rec_energy_numu_mc) \
  X(hep::rec_hdr) \
  X(hep::rec_mc) \
  X(hep::rec_mc_allcosmics) \
  X(hep::rec_mc_allcosmics_michel) \
  X(hep::rec_mc_allnus) \
  X(hep::rec_mc_allnus_beam) \
  X(hep::rec_mc_allnus_genVersion) \
  X(hep::rec_mc_allnus_michel) \
  X(hep::rec_mc_allnus_prim) \
  X(hep::rec_mc_allnus_prim_daughterlist) \
  X(hep::rec_mc_allnus_rwgt_genie) \
  X(hep::rec_mc_allnus_rwgt_ppfx) \
  X(hep::rec_mc_allnus_rwgt_ppfx_vuniv) \
  X(hep::rec_mc_cosmic) \
  X(hep::rec_mc_cosmic_michel) \
  X(hep::rec_mc_global) \
  X(hep::rec_mc_nu) \
  X(hep::rec_mc_nu_beam) \
  X(hep::rec_mc_nu_genVersion) \
  X(hep::rec_mc_nu_michel) \
  X(hep::rec_mc_nu_prim) \
  X(hep::rec_mc_nu_prim_daughterlist) \
  X(hep::rec_mc_nu_rwgt_genie) \
  X(hep::rec_mc_nu_rwgt_ppfx) \
  X(hep::rec_mc_nu_rwgt_ppfx_vuniv) \
  X(hep::rec_me) \
  X(hep::rec_me_slc) \
  X(hep::rec_me_slc_truth) \
  X(hep::rec_me_slc_truth_daughterlist) \
  X(hep::rec_me_slc_truth_motherlist) \
  X(hep::rec_me_trkbpf) \
  X(hep::rec_me_trkbpf_truth) \
  X(hep::rec_me_trkbpf_truth_daughterlist) \
  X(hep::rec_me_trkbpf_truth_motherlist) \
  X(hep::rec_me_trkcosmic) \
  X(hep::rec_me_trkcosmic_truth) \
  X(hep::rec_me_trkcosmic_truth_daughterlist) \
  X(hep::rec_me_trkcosmic_truth_motherlist) \
  X(hep::rec_me_trkdiscrete) \
  X(hep::rec_me_trkdiscrete_truth) \
  X(hep::rec_me_trkdiscrete_truth_daughterlist) \
  X(hep::rec_me_trkdiscrete_truth_motherlist) \
  X(hep::rec_me_trkkalman) \
  X(hep::rec_me_trkkalman_truth) \
  X(hep::rec_me_trkkalman_truth_daughterlist) \
  X(hep::rec_me_trkkalman_truth_motherlist) \
  X(hep::rec_parent_mrccpar) \
  X(hep::rec_sand_nd) \
  X(hep::rec_sand_nue) \
  X(hep::rec_sand_nue_jm) \
  X(hep::rec_sand_nue_jmid) \
  X(hep::rec_sand_numu) \
  X(hep::rec_sand_nus) \
  X(hep::rec_sel_bpfid) \
  X(hep::rec_sel_contain) \
  X(hep::rec_sel_cosrej) \
  X(hep::rec_sel_cvn) \
  X(hep::rec_sel_cvn_output) \
  X(hep::rec_sel_cvn2017) \
  X(hep::rec_sel_cvn2017_output) \
  X(hep::rec_sel_cvnProd3Train) \
  X(hep::rec_sel_cvnProd3Train_output) \
  X(hep::rec_sel_lem) \
  X(hep::rec_sel_lid) \
  X(hep::rec_sel_nccosrej) \
  X(hep::rec_sel_ncpi0bkgrej) \
  X(hep::rec_sel_nuecosrej) \
  X(hep::rec_sel_nuepre) \
  X(hep::rec_sel_qepid) \
  X(hep::rec_sel_remid) \
  X(hep::rec_sel_remid2017) \
  X(hep::rec_sel_rvp) \
  X(hep::rec_sel_veto) \
  X(hep::rec_sel_xnuepid) \
  X(hep::rec_slc) \
  X(hep::rec_spill) \
  X(hep::rec_spill_bposx) \
  X(hep::rec_spill_bposy) \
  X(hep::rec_spill_intx) \
  X(hep::rec_spill_inty) \
  X(hep::rec_training_cvnfeatures) \
  X(hep::rec_training_cvnfeatures_components) \
  X(hep::rec_training_cvnfeatures_output) \
  X(hep::rec_training_cvnmaps) \
  X(hep::rec_training_slicemaps) \
  X(hep::rec_trk_bpf) \
  X(hep::rec_trk_bpf_tracks) \
  X(hep::rec_trk_bpf_tracks_me) \
  X(hep::rec_trk_bpf_tracks_me_truth) \
  X(hep::rec_trk_bpf_tracks_me_truth_daughterlist) \
  X(hep::rec_trk_bpf_tracks_me_truth_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem) \
  X(hep::rec_trk_bpf_tracks_mrbrem_cvn) \
  X(hep::rec_trk_bpf_tracks_mrbrem_cvn_output) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_lid) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_lidE) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truth) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truth_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truthXView) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truthYView) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truth) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truth_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truth_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truthXView) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truthXView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truthXView_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truthYView) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truthYView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrbrem_truthYView_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrdif) \
  X(hep::rec_trk_bpf_tracks_mrdif_cvn) \
  X(hep::rec_trk_bpf_tracks_mrdif_cvn_output) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_lid) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_lidE) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truth) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truth_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truth_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truthXView) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truthYView) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_truth) \
  X(hep::rec_trk_bpf_tracks_mrdif_truth_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_truth_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_truthXView) \
  X(hep::rec_trk_bpf_tracks_mrdif_truthXView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_truthXView_motherlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_truthYView) \
  X(hep::rec_trk_bpf_tracks_mrdif_truthYView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_mrdif_truthYView_motherlist) \
  X(hep::rec_trk_bpf_tracks_truth) \
  X(hep::rec_trk_bpf_tracks_truth_daughterlist) \
  X(hep::rec_trk_bpf_tracks_truth_motherlist) \
  X(hep::rec_trk_bpf_tracks_truthXView) \
  X(hep::rec_trk_bpf_tracks_truthXView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_truthXView_motherlist) \
  X(hep::rec_trk_bpf_tracks_truthYView) \
  X(hep::rec_trk_bpf_tracks_truthYView_daughterlist) \
  X(hep::rec_trk_bpf_tracks_truthYView_motherlist) \
  X(hep::rec_trk_cosmic) \
  X(hep::rec_trk_cosmic_tracks) \
  X(hep::rec_trk_cosmic_tracks_me) \
  X(hep::rec_trk_cosmic_tracks_me_truth) \
  X(hep::rec_trk_cosmic_tracks_me_truth_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_me_truth_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_cvn) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_cvn_output) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_lid) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_lidE) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truth) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truth_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truthXView) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truthYView) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truth) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truth_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truth_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truthXView) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truthXView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truthXView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truthYView) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truthYView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrbrem_truthYView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif) \
  X(hep::rec_trk_cosmic_tracks_mrdif_cvn) \
  X(hep::rec_trk_cosmic_tracks_mrdif_cvn_output) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_lid) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_lidE) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truth) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truth_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truth_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truthXView) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truthYView) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truth) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truth_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truth_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truthXView) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truthXView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truthXView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truthYView) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truthYView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_mrdif_truthYView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_truth) \
  X(hep::rec_trk_cosmic_tracks_truth_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_truth_motherlist) \
  X(hep::rec_trk_cosmic_tracks_truthXView) \
  X(hep::rec_trk_cosmic_tracks_truthXView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_truthXView_motherlist) \
  X(hep::rec_trk_cosmic_tracks_truthYView) \
  X(hep::rec_trk_cosmic_tracks_truthYView_daughterlist) \
  X(hep::rec_trk_cosmic_tracks_truthYView_motherlist) \
  X(hep::rec_trk_discrete) \
  X(hep::rec_trk_discrete_tracks) \
  X(hep::rec_trk_discrete_tracks_me) \
  X(hep::rec_trk_discrete_tracks_me_truth) \
  X(hep::rec_trk_discrete_tracks_me_truth_daughterlist) \
  X(hep::rec_trk_discrete_tracks_me_truth_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem) \
  X(hep::rec_trk_discrete_tracks_mrbrem_cvn) \
  X(hep::rec_trk_discrete_tracks_mrbrem_cvn_output) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_lid) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_lidE) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truth) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truth_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truthXView) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truthYView) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truth) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truth_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truth_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truthXView) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truthXView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truthXView_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truthYView) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truthYView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrbrem_truthYView_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrdif) \
  X(hep::rec_trk_discrete_tracks_mrdif_cvn) \
  X(hep::rec_trk_discrete_tracks_mrdif_cvn_output) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_lid) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_lidE) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truth) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truth_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truth_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truthXView) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truthYView) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_truth) \
  X(hep::rec_trk_discrete_tracks_mrdif_truth_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_truth_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_truthXView) \
  X(hep::rec_trk_discrete_tracks_mrdif_truthXView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_truthXView_motherlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_truthYView) \
  X(hep::rec_trk_discrete_tracks_mrdif_truthYView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_mrdif_truthYView_motherlist) \
  X(hep::rec_trk_discrete_tracks_truth) \
  X(hep::rec_trk_discrete_tracks_truth_daughterlist) \
  X(hep::rec_trk_discrete_tracks_truth_motherlist) \
  X(hep::rec_trk_discrete_tracks_truthXView) \
  X(hep::rec_trk_discrete_tracks_truthXView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_truthXView_motherlist) \
  X(hep::rec_trk_discrete_tracks_truthYView) \
  X(hep::rec_trk_discrete_tracks_truthYView_daughterlist) \
  X(hep::rec_trk_discrete_tracks_truthYView_motherlist) \
  X(hep::rec_trk_kalman) \
  X(hep::rec_trk_kalman_tracks) \
  X(hep::rec_trk_kalman_tracks_me) \
  X(hep::rec_trk_kalman_tracks_me_truth) \
  X(hep::rec_trk_kalman_tracks_me_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks_me_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem) \
  X(hep::rec_trk_kalman_tracks_mrbrem_cvn) \
  X(hep::rec_trk_kalman_tracks_mrbrem_cvn_output) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_lid) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_lidE) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truth) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truthXView) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truthYView) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truth) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truthXView) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truthYView) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrbrem_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrdif) \
  X(hep::rec_trk_kalman_tracks_mrdif_cvn) \
  X(hep::rec_trk_kalman_tracks_mrdif_cvn_output) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_lid) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_lidE) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truth) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truthXView) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truthYView) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_truth) \
  X(hep::rec_trk_kalman_tracks_mrdif_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_truthXView) \
  X(hep::rec_trk_kalman_tracks_mrdif_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_truthYView) \
  X(hep::rec_trk_kalman_tracks_mrdif_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_mrdif_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks_truth) \
  X(hep::rec_trk_kalman_tracks_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks_truthXView) \
  X(hep::rec_trk_kalman_tracks_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks_truthYView) \
  X(hep::rec_trk_kalman_tracks_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d) \
  X(hep::rec_trk_kalman_tracks2d_me) \
  X(hep::rec_trk_kalman_tracks2d_me_truth) \
  X(hep::rec_trk_kalman_tracks2d_me_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_me_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_cvn) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_cvn_output) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_lid) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_lidE) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truth) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truthXView) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truthYView) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truth) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truthXView) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truthYView) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrbrem_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_cvn) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_cvn_output) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_lid) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_lidE) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truth) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truthXView) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truthYView) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truth) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truthXView) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truthYView) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_mrdif_truthYView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_truth) \
  X(hep::rec_trk_kalman_tracks2d_truth_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_truth_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_truthXView) \
  X(hep::rec_trk_kalman_tracks2d_truthXView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_truthXView_motherlist) \
  X(hep::rec_trk_kalman_tracks2d_truthYView) \
  X(hep::rec_trk_kalman_tracks2d_truthYView_daughterlist) \
  X(hep::rec_trk_kalman_tracks2d_truthYView_motherlist) \
  X(hep::rec_trk_window) \
  X(hep::rec_trk_window_tracks) \
  X(hep::rec_trk_window_tracks_me) \
  X(hep::rec_trk_window_tracks_me_truth) \
  X(hep::rec_trk_window_tracks_me_truth_daughterlist) \
  X(hep::rec_trk_window_tracks_me_truth_motherlist) \
  X(hep::rec_trk_window_tracks_mrbrem) \
  X(hep::rec_trk_window_tracks_mrbrem_cvn) \
  X(hep::rec_trk_window_tracks_mrbrem_cvn_output) \
  X(hep::rec_trk_window_tracks_mrbrem_lid) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_lid) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_lidE) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truth) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truth_motherlist) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truthXView) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truthYView) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_trk_window_tracks_mrbrem_truth) \
  X(hep::rec_trk_window_tracks_mrbrem_truth_daughterlist) \
  X(hep::rec_trk_window_tracks_mrbrem_truth_motherlist) \
  X(hep::rec_trk_window_tracks_mrbrem_truthXView) \
  X(hep::rec_trk_window_tracks_mrbrem_truthXView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrbrem_truthXView_motherlist) \
  X(hep::rec_trk_window_tracks_mrbrem_truthYView) \
  X(hep::rec_trk_window_tracks_mrbrem_truthYView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrbrem_truthYView_motherlist) \
  X(hep::rec_trk_window_tracks_mrdif) \
  X(hep::rec_trk_window_tracks_mrdif_cvn) \
  X(hep::rec_trk_window_tracks_mrdif_cvn_output) \
  X(hep::rec_trk_window_tracks_mrdif_lid) \
  X(hep::rec_trk_window_tracks_mrdif_lid_lid) \
  X(hep::rec_trk_window_tracks_mrdif_lid_lidE) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truth) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truth_daughterlist) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truth_motherlist) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truthXView) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truthYView) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_trk_window_tracks_mrdif_truth) \
  X(hep::rec_trk_window_tracks_mrdif_truth_daughterlist) \
  X(hep::rec_trk_window_tracks_mrdif_truth_motherlist) \
  X(hep::rec_trk_window_tracks_mrdif_truthXView) \
  X(hep::rec_trk_window_tracks_mrdif_truthXView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrdif_truthXView_motherlist) \
  X(hep::rec_trk_window_tracks_mrdif_truthYView) \
  X(hep::rec_trk_window_tracks_mrdif_truthYView_daughterlist) \
  X(hep::rec_trk_window_tracks_mrdif_truthYView_motherlist) \
  X(hep::rec_trk_window_tracks_truth) \
  X(hep::rec_trk_window_tracks_truth_daughterlist) \
  X(hep::rec_trk_window_tracks_truth_motherlist) \
  X(hep::rec_trk_window_tracks_truthXView) \
  X(hep::rec_trk_window_tracks_truthXView_daughterlist) \
  X(hep::rec_trk_window_tracks_truthXView_motherlist) \
  X(hep::rec_trk_window_tracks_truthYView) \
  X(hep::rec_trk_window_tracks_truthYView_daughterlist) \
  X(hep::rec_trk_window_tracks_truthYView_motherlist) \
  X(hep::rec_vtx) \
  X(hep::rec_vtx_elastic) \
  X(hep::rec_vtx_elastic_fuzzyk) \
  X(hep::rec_vtx_elastic_fuzzyk_png) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_me) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_me_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_me_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_me_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_cvn) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_cvn_output) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_lid) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_lidE) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrbrem_truthYView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_cvn) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_cvn_output) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_lid) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_lidE) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_mrdif_truthYView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_bpf_truthYView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnmaps) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpart) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpart2FlatFlux) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpart2FlatFluxBal) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpart2GenieLike) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpart2GenieLikeBal) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpart2View) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpart2ViewBal) \
  X(hep::rec_vtx_elastic_fuzzyk_png_cvnpartBal) \
  X(hep::rec_vtx_elastic_fuzzyk_png_regcvn) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_lid) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_lidE) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_shwlid_truthYView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_truthYView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png_xsec) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truth) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truth_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truth_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truthXView) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truthXView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truthXView_motherlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truthYView) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truthYView_daughterlist) \
  X(hep::rec_vtx_elastic_fuzzyk_png2d_truthYView_motherlist) \
  X(hep::rec_vtx_hough) \
  X(hep::rec_vtx_hough_fuzzyk) \
  X(hep::rec_vtx_hough_fuzzyk_png) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_me) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_me_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_me_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_me_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_cvn) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_cvn_output) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_lid) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_lidE) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_lid_truthYView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrbrem_truthYView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_cvn) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_cvn_output) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_lid) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_lidE) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_lid_truthYView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_mrdif_truthYView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_bpf_truthYView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnmaps) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpart) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpart2FlatFlux) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpart2FlatFluxBal) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpart2GenieLike) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpart2GenieLikeBal) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpart2View) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpart2ViewBal) \
  X(hep::rec_vtx_hough_fuzzyk_png_cvnpartBal) \
  X(hep::rec_vtx_hough_fuzzyk_png_regcvn) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_lid) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_lidE) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_shwlid_truthYView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_truthYView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png_xsec) \
  X(hep::rec_vtx_hough_fuzzyk_png2d) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truth) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truth_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truth_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truthXView) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truthXView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truthXView_motherlist) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truthYView) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truthYView_daughterlist) \
  X(hep::rec_vtx_hough_fuzzyk_png2d_truthYView_motherlist) \
  X(hep::rec_vtx_vdt) \
  X(hep::spill) \
  X(hep::spill_bposx) \
  X(hep::spill_bposy) \
  X(hep::spill_intx) \
  X(hep::spill_inty)
